language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python3 -m unittest discover
  - python3 -m unittest distributipy/tests/test_distribution_checks.py
  - python3 -m unittest distributipy/tests/test_distribution_fitter.py
  - coverage run -m unittest discover
after_success:
  - codecov
