language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python -m unittest discover
  - coverage run -m unittest discover
after_success:
  - codecov
